### ISSUE TITLE
Configuration Endpoint does not resolve when using Custom Domains

### ISSUE THREAD

**Issue by davejhahn** [Azure/api-management-self-hosted-gateway#164]
### Report

When using custom domain names, the DNS for the original Azure provided names no longer resolve (e.g. [instance].developer.azure-api.net).  When deploying a self-hosted gateway to Kubernetes, it cannot resolve the name so the pod fails to start.

### Expected Behavior

After deploying (via helm or other), the pod should be able to communicate with the configuration.azure-api.net name and complete the configuration.

### Actual Behavior

When deploying self-hosted gateways, since there is no custom domain option provided for [instance].configuration.azure-api.net, it is unable to connect and configure.

### Steps to Reproduce the Problem

1. Create APIM
2. Test Azure provided DNS for management, gateway, development portal & ensure they are working
3. Add custom domains for management, gateway, and development portal
4. Test & ensure custom domains work
5. Test original Azure provided names, they do not resolve, including [instance].configuration.azure-api.net

### Logs from self-hosted gateway

```
[31m[Error]2022-10-12T02:54:48.369 [ConfigInitialSyncFailed], exception: Gateway.Configuration.ConfigurationNotFoundException: /apim/config/snapshot.lock.json
   at Gateway.Configuration.FileSystem.FileConfigurationProvider`1.GetAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration.FileSystem\FileConfigurationProvider.cs:line 35
   at Gateway.Host.AspNetCore.ExternalConfiguration.BackwardsCompatibility.ConfigurationProviderWithFallback.GetConfigurationFromFallbackProvider(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\BackwardsCompatibility\ConfigurationProviderWithFallback.cs:line 59
   at Gateway.Host.AspNetCore.ExternalConfiguration.BackwardsCompatibility.ConfigurationProviderWithFallback.GetAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\BackwardsCompatibility\ConfigurationProviderWithFallback.cs:line 47
   at Microsoft.WindowsAzure.ApiManagement.Proxy.Gateway.Configuration.ConfigurationRepositoryProvider.RestoreSnapshotAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration\ConfigurationRepositoryProvider.cs:line 134
   at Microsoft.WindowsAzure.ApiManagement.Proxy.Gateway.Configuration.ConfigurationRepositoryProvider.StartAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration\ConfigurationRepositoryProvider.cs:line 181, source: ConfigurationRepositoryProvider[0m
[31m[Error]2022-10-12T02:54:58.376 [ConfigInitialSyncFailed], exception: Gateway.Configuration.ConfigurationNotFoundException: /apim/config/snapshot.lock.json
   at Gateway.Configuration.FileSystem.FileConfigurationProvider`1.GetAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration.FileSystem\FileConfigurationProvider.cs:line 35
   at Gateway.Host.AspNetCore.ExternalConfiguration.BackwardsCompatibility.ConfigurationProviderWithFallback.GetConfigurationFromFallbackProvider(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\BackwardsCompatibility\ConfigurationProviderWithFallback.cs:line 59
   at Gateway.Host.AspNetCore.ExternalConfiguration.BackwardsCompatibility.ConfigurationProviderWithFallback.GetAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\BackwardsCompatibility\ConfigurationProviderWithFallback.cs:line 47
   at Microsoft.WindowsAzure.ApiManagement.Proxy.Gateway.Configuration.ConfigurationRepositoryProvider.RestoreSnapshotAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration\ConfigurationRepositoryProvider.cs:line 134
   at Microsoft.WindowsAzure.ApiManagement.Proxy.Gateway.Configuration.ConfigurationRepositoryProvider.StartAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration\ConfigurationRepositoryProvider.cs:line 181, source: ConfigurationRepositoryProvider[0m
[37m[Info] 2022-10-12T02:54:58.367 [LoadingConfigurationSnapshot], message: uri: https://XXXXXXXXXXXXXXX.configuration.azure-api.net//gateways/dapr/snapshot, request-id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX, source: ConfigurationApiClient[0m
[33m[Warn] 2022-10-12T02:54:58.374 [ConfigurationApiV2NotAvailable], message: The configuration V2 API is not reachable on https://XXXXXXXXXXXXXXX.configuration.azure-api.net/gateways/dapr/snapshot, source: ConfigurationApiClient[0m
[33m[Warn] 2022-10-12T02:54:58.376 [ConfigurationNotAvailable], exception: Gateway.Configuration.Client.Exceptions.ServiceUnreachableException: The configuration V2 API is not reachable on https://XXXXXXXXXXXXXXX.configuration.azure-api.net/gateways/dapr/snapshot
 ---> System.Net.Http.HttpRequestException: Name does not resolve (XXXXXXXXXXXXXXX.configuration.azure-api.net:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Gateway.Configuration.Client.ConfigurationApiClient.SendRequestToApiAsync(HttpRequestMessage req, CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration.Client\ConfigurationApiClient.cs:line 161
   --- End of inner exception stack trace ---
   at Gateway.Configuration.Client.ConfigurationApiClient.SendRequestToApiAsync(HttpRequestMessage req, CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration.Client\ConfigurationApiClient.cs:line 187
   at Gateway.Configuration.Client.ConfigurationApiClient.GetSnapshotAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration.Client\ConfigurationApiClient.cs:line 91
   at Gateway.Configuration.Client.ConfigurationApiV2Provider.GetAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration.Client\ConfigurationApiV2Provider.cs:line 49
   at Gateway.Host.AspNetCore.ExternalConfiguration.BackwardsCompatibility.ConfigurationProviderWithBackwardsCompatibility.GetFromV2ConfigurationApi(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\BackwardsCompatibility\ConfigurationProviderWithBackwardsCompatibility.cs:line 152
   at Gateway.Host.AspNetCore.ExternalConfiguration.BackwardsCompatibility.ConfigurationProviderWithBackwardsCompatibility.GetAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\BackwardsCompatibility\ConfigurationProviderWithBackwardsCompatibility.cs:line 49
   at Gateway.Host.AspNetCore.ExternalConfiguration.BackwardsCompatibility.ConfigurationProviderWithFallback.GetAsync(CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\BackwardsCompatibility\ConfigurationProviderWithFallback.cs:line 42, source: ConfigurationProviderWithFallback[0m
[37m[Info] 2022-10-12T02:54:58.376 [TryingBackupConfiguration], message: file, info: /apim/config/snapshot.lock.json, data: /apim/config/snapshot.json.gzip, source: ConfigurationProviderWithFallback[0m
[37m[Info] 2022-10-12T02:54:58.376 [LocalBackupLoading], message: /apim/config/snapshot.lock.json, source: FileConfigurationProvider[0m
[33m[Warn] 2022-10-12T02:54:58.376 [LocalBackupLocationNotFound], message: /apim/config, source: FileConfigurationProvider[0m
```

### Self-hosted Gateway Version

2.1.4

### Deployment

Self-Managed (YAML/Helm)

### Platform

Microsoft Azure

### Kubernetes Version

Other

### Anything else?

Kubernetes version 1.23.8

**Comment by tomkerkhove** [comment]
Given this is mainly around custom domain names and self-hosted gateway, the recommendation is to open an Azure Support ticket.

With regards to the Configuration API v2; custom domain names are not supported for now indeed as documented on [aka.ms/apim/shgw/migration/v2#known-limitations](https://aka.ms/apim/shgw/migration/v2#known-limitations)

**Comment by tomkerkhove** [comment]
Also, what is your service name? Azure Support should be able to help you with it.

**Comment by davejhahn** [comment]
I will open a support ticket.  I guess I'm curious if anyone has configured both custom DNS names for APIM and then deployed the self-hosted gateway into AKS.   Seems like it would be a common scenario that someone would have already encountered.

Without the custom domains, it works fine--the configuration endpoint (as well as the other endpoints) resolve via DNS and are accessible.  With custom domains, it appears to remove the azure generated names from being recognized both by DNS as well as APIM itself (tested APIM not recognizing by what I noted, adding an alias on a pod and having the Azure name resolve properly, but still not being acknowledged as valid by APIM).  

It almost appears that with custom domains you cannot use self-hosted gateways, which is a problem.

**Comment by tomkerkhove** [comment]
> It almost appears that with custom domains you cannot use self-hosted gateways, which is a problem.

This is a known limitation of Configuration API v2 and is coming later on because it enforces the `.configuration.azure-api.net` endpoint. However, DNS should resolve and thus a support ticket is recommended though.

**Comment by tomkerkhove** [comment]
Why is your APIM service name?

**Comment by tomkerkhove** [comment]
I'm not able to check for you as I need the APIM service name but if you are using internal VNET, then this is by design.

However, given Configuration API v2 does not support custom domain names you can use `hostAliases` as a workaround as per our docs:

https://learn.microsoft.com/en-gb/azure/api-management/how-to-self-hosted-gateway-on-kubernetes-in-production#custom-domain-names-and-ssl-certificates

**Comment by tomkerkhove** [comment]
@davejhahn Any input on this? Did Azure support help you?

**Comment by tomkerkhove** [comment]
Any updates @davejhahn?

**Comment by tomkerkhove** [comment]
Closing due to inactivity, feel free to re-open if need be.

**Comment by Leonardo-Ferreira** [comment]
Im having the same issue... `myApimNameHere.configuration.azure-api.net` does not resolve so the pod never gets up... not in the pod, not in my local machine, not anywhere

**Comment by tomkerkhove** [comment]
Can you open a support ticket please?
