### ISSUE TITLE
Getting constant errors in the logs not related to setup

### ISSUE THREAD

**Issue by MehtaAadi** [Azure/api-management-self-hosted-gateway#171]
### Report

Getting error in the docker logs. 

### Expected Behavior

No errors

### Actual Behavior

These are logs related to issues with Azure API Management

### Steps to Reproduce the Problem

Just configure ratelimiting on azure management portal.

### Logs from self-hosted gateway

```
[Info] 2022-10-23T10:13:12.907 [QuotaCounterGlobalSyncStart], message: Started quota-by-key synchronization. There are '1' counters existing now., source: QuotaByKeyCounterService
[Info] 2022-10-23T10:13:12.908 [QuotaCounterGlobalSyncSendUpdate], message: Sending '1' counter updates to global-sync azure infra cloud storage., source: QuotaByKeyCounterService
[Warn] 2022-10-23T10:13:12.930 [TransactionalTableStorageSaveBatchFailed], message: Partition Key: 4, Transaction ID: , Transaction Index: 1, RowKey: , exception: Microsoft.Azure.Cosmos.Table.StorageException: Not Found
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.Azure.ApiManagement.Infra.Cloud.Storage.TransactionalTable`1.ExecuteQueryAsync(TableQuery`1 query, CancellationToken cancellationToken)
   at Microsoft.Azure.ApiManagement.Infra.Cloud.Storage.TransactionalTable`1.<>c__DisplayClass22_1.<<SaveBatchAsync>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Azure.ApiManagement.Infra.Cloud.Storage.TransactionalTable`1.SaveBatchAsync(String partitionKey, String transactionId, Int32 transactionIndex, List`1 entityBatch, CancellationToken cancellationToken)
Request Information
RequestID:b05a2198-7002-0073-1bc8-e66e00000000
RequestDate:Sun, 23 Oct 2022 10:13:12 GMT
StatusMessage:Not Found
ErrorCode:
ErrorMessage:The table specified does not exist.
RequestId:b05a2198-7002-0073-1bc8-e66e00000000
Time:2022-10-23T10:13:12.9219563Z
, source: CountersStorageController
[Warn] 2022-10-23T10:13:12.934 [CounterSyncStorageFailed], exception: Microsoft.Azure.Cosmos.Table.StorageException: Not Found
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.Azure.ApiManagement.Infra.Cloud.Storage.TransactionalTable`1.ExecuteQueryAsync(TableQuery`1 query, CancellationToken cancellationToken)
   at Microsoft.Azure.ApiManagement.Infra.Cloud.Storage.TransactionalTable`1.<>c__DisplayClass22_1.<<SaveBatchAsync>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Azure.ApiManagement.Infra.Cloud.Storage.TransactionalTable`1.SaveBatchAsync(String partitionKey, String transactionId, Int32 transactionIndex, List`1 entityBatch, CancellationToken cancellationToken)
   at Microsoft.Azure.ApiManagement.Infra.Cloud.Storage.TransactionalTable`1.Throttle[TResult](Func`2 task, SemaphoreSlim throttle, CancellationToken cancellationToken)
   at Microsoft.Azure.ApiManagement.Infra.Cloud.Storage.TransactionalTable`1.SaveAsync(String partitionKey, IEnumerable`1 entities, String transactionId, CancellationToken cancellationToken)
   at Gateway.Configuration.Client.ConfigurationServiceTableStorageWrapper`1.ExecuteAsync[TResult](Func`3 action, CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Configuration.Client\ConfigurationServiceTableStorageWrapper.cs:line 65
   at Gateway.Host.AspNetCore.ExternalConfiguration.BackwardsCompatibility.LazyTransactionalTable.SaveAsync(String partitionKey, IEnumerable`1 entities, String transactionId, CancellationToken cancellationToken) in D:\a\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\BackwardsCompatibility\LazyTransactionalTable.cs:line 43
   at Microsoft.WindowsAzure.ApiManagement.Proxy.Api.Controllers.CountersStorageController.SynchronizeAsync(IEnumerable`1 counters, String batchId) in D:\a\1\s\Proxy\Gateway.Policies.Quota\CountersStorageController.cs:line 73
   at Microsoft.WindowsAzure.ApiManagement.Proxy.Api.Controllers.CountersStorageController.ExchangeCounterStatesAsync(SmartCountersUpdateSet updateSet) in D:\a\1\s\Proxy\Gateway.Policies.Quota\CountersStorageController.cs:line 39
   at Gateway.Quota.Services.QuotaByKeyCounterService.PerformSynchronization(Nullable`1 lastSyncTime, CancellationToken cancellation) in D:\a\1\s\Proxy\Gateway.Policies.Quota\Services\QuotaByKeyCounterService.cs:line 212
   at Gateway.Quota.Services.QuotaByKeyCounterService.Synchronize() in D:\a\1\s\Proxy\Gateway.Policies.Quota\Services\QuotaByKeyCounterService.cs:line 81
Request Information
RequestID:b05a2198-7002-0073-1bc8-e66e00000000
RequestDate:Sun, 23 Oct 2022 10:13:12 GMT
StatusMessage:Not Found
ErrorCode:
ErrorMessage:The table specified does not exist.
RequestId:b05a2198-7002-0073-1bc8-e66e00000000
Time:2022-10-23T10:13:12.9219563Z
, source: QuotaByKeyCounterService
```

### Self-hosted Gateway Version

2.1.0, 2.1.6

### Deployment

Docker (Compose)

### Platform

Amazon Web Services

**Comment by tomkerkhove** [comment]
It looks like it's not able to synchronize things due to quotas. What Configuration API are you using?

**Comment by tomkerkhove** [comment]
@Andrei-Predoiu Any input on this?

**Comment by tomkerkhove** [comment]
Closing due to inactivity, feel free to open a support ticket if this problem is still occuring.
