### ISSUE TITLE
api management gateway how to offline restart with backup snapshot ?

### ISSUE THREAD

**Issue by Restry** [Azure/api-management-self-hosted-gateway#34]
https://docs.microsoft.com/en-us/azure/api-management/self-hosted-gateway-overview

i'm not very sure it this description means the gateway can be able to start without internet ? if they have been run with the backup ?

_When configuration backup is turned on and connectivity to Azure is interrupted:

Running self-hosted gateways will continue to function using an in-memory copy of the configuration
Stopped self-hosted gateways will be able to start using a backup copy of the configuration_

i have try it in my local docker container, the snapshot it's already created in the path "/apim/config",
after offline and restart container , it throw error :

would you help me resolve this problem ? 
thanks 

`
[Error]2021-07-8T01:46:52.274 [Error], exception: System.Net.Http.HttpRequestException: Name does not resolve

---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve

at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

--- End of inner exception stack trace ---

at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

at Gateway.Host.AspNetCore.ExternalConfiguration.ServiceConfigurationSource.<>c__DisplayClass17_0.<<UpdateConfiguration>b__1>d.MoveNext() in C:\azp\agent\_work\1\s\Proxy\Gateway.Host.AspNetCore\ExternalConfiguration\ServiceConfigurationSource.cs:line 166

--- End of stack trace from previous location where exception was thrown ---

at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext), source: ServiceConfigurationSource

`

**Comment by obautista** [comment]
> /apim/config

@Restry - we are testing the exact thing you posted about.  Were you able to learn anything?  We set up self hosted gateway using Docker and a backed up config file snapshot.  API call through self hosted gateway stopped working after restarting container.
