### ISSUE TITLE
APIM Config Backup with PersistentVolumeClaim

### ISSUE THREAD

**Issue by stfnbstl** [Azure/api-management-self-hosted-gateway#83]
### Report

I have rewritten the deployment manifest to offload the config backup to a persistent volume. This should help the config persist when pods are restarted during an internet outage.
However, I get an access error because all folders in the backup path belong to the root user and the pod is read-only.
I don't want to run my pod in the root context and I think this behavior should be changed, so that the path is owned by the apimuser.

### Expected Behavior

The backup file should be created at path /apim/config

### Actual Behavior

I get an `UnauthorizedAccessException`

### Steps to Reproduce the Problem

1. Deploy the SHG as a StatefulSet (see YAML manifest below)
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: shg-env
data:
  config.service.endpoint: "https://xxxx"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shg
spec:
  selector:
    matchLabels:
      app: shg
  serviceName: shg
  replicas: 3
  template:
    metadata:
      labels:
        app: shg
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - shg
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      containers:
      - name: shg
        image: mcr.microsoft.com/azure-api-management/gateway:1.2.5
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: shg-token
              key: value
        envFrom:
        - configMapRef:
            name: shg-env
        volumeMounts:
        - name: shg-pvc
          mountPath: /apim/config
  volumeClaimTemplates:
  - metadata:
      name: shg-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: shg
spec:
  type: LoadBalancer
  loadBalancerIP: x.x.x.x
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: shg
```
2. Check the logs for the error below.

### Logs from self-hosted gateway

```
[Info] 2022-03-22T07:43:42.446 [LocalBackupStarted], message: /apim/config/snapshot.lock.json, source: FileBackupProvider
16
[Warn] 2022-03-22T07:43:42.447 [LocalBackupFileOpenFailed], message: /apim/config/snapshot.lock.json, exception: System.UnauthorizedAccessException: Access to the path '/apim/config/snapshot.lock.json' is denied.
15
 ---> System.IO.IOException: Permission denied
14
   --- End of inner exception stack trace ---
13
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
12
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
11
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
10
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
9
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
8
   at Gateway.Configuration.FileSystem.FileProviderBase.<>c__DisplayClass13_0.<TryOpen>b__2() in D:\a\1\s\Proxy\Gateway.Configuration.FileSystem\FileProviderBase.cs:line 97
7
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
6
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
5
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
4
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
3
   at Polly.Policy.Execute[TResult](Func`1 action)
2
   at Gateway.Configuration.FileSystem.FileProviderBase.TryOpen(String filePath, FileMode mode, FileStream& res) in D:\a\1\s\Proxy\Gateway.Configuration.FileSystem\FileProviderBase.cs:line 97, source: FileBackupProvider
1
[Info] 2022-03-22T07:43:42.447 [EventSnapshotWasNotCreated], source: ConfigurationRepositoryProvider
```

### Self-hosted Gateway Version

1.2.5

### Deployment

Self-Managed (YAML/Helm)

### Platform

Other

### Kubernetes Version

1.20

**Comment by stfnbstl** [comment]
Nevermind, i just found a way of getting this to work. All you have to do is to add `securityContext.fsGroup` and set it to `1001`:

```yaml
...
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - shg
        topologyKey: kubernetes.io/hostname
  securityContext:
    fsGroup: 1001
...
```

The creation now works:
```
[Info] 2022-03-22T09:14:29.427 [LocalBackupStarted], message: /apim/config/snapshot.lock.json, source: FileBackupProvider
[Info] 2022-03-22T09:14:29.427 [LocalBackupFileOpened], message: /apim/config/snapshot.lock.json, source: FileBackupProvider
[Info] 2022-03-22T09:14:29.427 [LocalBackupFileOpened], message: /apim/config/snapshot.json.gzip, source: FileBackupProvider
[Info] 2022-03-22T09:14:31.100 [LocalBackupCreatedSuccessfully], message: /apim/config/snapshot.json.gzip, source: FileBackupProvider
```
Unfortunately your CSI driver must support this via [fsGroupPolicy](https://kubernetes-csi.github.io/docs/csi-driver-object.html#:~:text=Info%20on%20Mount.-,fsGroupPolicy,-This%20field%20was). If this was set to `None` in your CSI CRD, then I think the securityContext would not be a solution either.
For more Information on fsGroupPolicies see: [fsGroupPolicy](https://kubernetes-csi.github.io/docs/csi-driver-object.html#:~:text=Info%20on%20Mount.-,fsGroupPolicy,-This%20field%20was)

So I guess it's not exactly a bug but it should at least be mentioned in the official [documentation](https://docs.microsoft.com/en-us/azure/api-management/how-to-self-hosted-gateway-on-kubernetes-in-production#configuration-backup)

**Comment by stfnbstl** [comment]
> Thanks for circling back and sorry for the late reply but I was on paternity leave.
> 
> Would you mind sending a PR to improve the docs? Otherwise I'm happy to do so myself. https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/api-management/how-to-self-hosted-gateway-on-kubernetes-in-production.md

Sure thing, created a PR for the docs. #91726
